# Header
menu:
  首页: /#blog
  关于: /about
  归档: /archive

# Site favicon
favicon: /zhangyi.png

# Site logo
logo: /codanNew.png

# Enable Mathjax
mathjax: true

# Enable awesome-toc
awesome_toc: true

# Enable githubRepoWidget
github_repo_widget: false

# Social
social:
  github: someus
